INSERT INTO EXPENSE (NAME, AMOUNT, CATEGORY) VALUES ('Groceries', 120.50, 'Food');
INSERT INTO EXPENSE (NAME, AMOUNT, CATEGORY) VALUES ('Electricity Bill', 75.20, 'Utilities');
INSERT INTO EXPENSE (NAME, AMOUNT, CATEGORY) VALUES ('Internet', 60.00, 'Utilities');
INSERT INTO EXPENSE (NAME, AMOUNT, CATEGORY) VALUES ('Gym Membership', 45.99, 'Health');
INSERT INTO EXPENSE (NAME, AMOUNT, CATEGORY) VALUES ('Movie Tickets', 30.00, 'Entertainment');


INSERT INTO INCOME (NAME, AMOUNT, CATEGORY) VALUES ('Salary', 3500.00, 'Job');
INSERT INTO INCOME (NAME, AMOUNT, CATEGORY) VALUES ('Freelance Project', 850.00, 'Side Hustle');
INSERT INTO INCOME (NAME, AMOUNT, CATEGORY) VALUES ('Investment Return', 220.75, 'Investments');
INSERT INTO INCOME (NAME, AMOUNT, CATEGORY) VALUES ('Gift', 150.00, 'Other');
INSERT INTO INCOME (NAME, AMOUNT, CATEGORY) VALUES ('Bonus', 500.00, 'Job');
